### ISSUE TITLE
Tensorflow not recognizing GPU in Spyder 

### ISSUE THREAD

**Issue by WenTheProgrammer** [spyder-ide/spyder#20790]
I have followed this YouTube tutorial since I want to use GPU for tensorflow model training: https://www.youtube.com/watch?v=yLVFwAaFACk&ab_channel=DigitalSreeni. However, I was still not able to detect GPU of my computer in Spyder:
```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17504734730771000338
xla_global_id: -1
]
```
My system is Windows 11. My tensorflow version is 2.12.0. My GPUs are NVIDIA GeForce RTX 2060 and Intel® UHD Graphics 630. My NVIDIA CUDA version is 12.1. I used cudnn-windows-x86_64-8.8.1.3_cuda12-archive. My Anaconda is fully updated. My Spyder version is 5.4.2.
Any help will be much appreciated!

**Comment by GrayCyberWildman** [comment]
Starting from 2.11, the Windows builds of Tensorflow no longer support GPU, see:
https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0
Please downgrade to 2.10 instead.
Actually, I think this issue has nothing to do with Spyder. You can test your code in terminal, the output should be the same.

**Comment by dalthviz** [comment]
Hi @WenTheProgrammer thank you for the feedback and thank you @GrayCyberWildman for the info! I think as @GrayCyberWildman said there is not much to do from the Spyder side but let us know if downgrading Tensorflow helps!

**Comment by WenTheProgrammer** [comment]
Simply following the instructions in this link worked for me: https://www.tensorflow.org/install/pip#windows-native. 
However, the tricky thing is that now I have two Spyders installed in two environments (base, tf) respectively, I must open the right Spyder under the right environment (tf) using Anaconda Navigator or Anaconda Prompt to detect GPU, which is not very convenient. When I used Windows’ Spyder shortcut to open Spyder, even after changing the Spyder’s default environment to tf, Spyder would still give errors when I tried to detect GPU:
```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7124412856439104508
xla_global_id: -1
]

The system cannot find the path specified.
2023-04-11 20:17:54.575565: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-04-11 20:17:54.575609: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-04-11 20:17:56.319581: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-11 20:17:56.333535: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-04-11 20:17:56.333830: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2023-04-11 20:17:56.334106: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2023-04-11 20:17:56.334375: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2023-04-11 20:17:56.394671: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2023-04-11 20:17:56.394960: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2023-04-11 20:17:56.394976: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

**Comment by GrayCyberWildman** [comment]
I think maybe you can provide the output of "conda list" command in your base and tf environment for further information?

**Comment by dalthviz** [comment]
Running and submitting here the `conda list` output as @GrayCyberWildman mentioned could be worthy. Also, could you check if the correct version of `tensorflow` is the one being imported (so checking that `tensorflow` comes from your `tf` enviroment instead of the `base` environment)? You can do that by running from the Spyder IPython console:

    import tensorflow
    tensorflow.__version__

Maybe the error could be a module shadowing happening. [That was an issue in Spyder 5.4.2](https://github.com/spyder-ide/spyder/issues/20242) :thinking: Could you check the PYTHONPATH manager (`Tools > PYTHONPATH manager`) to see if any entry is there?

Any new info is appreciated. Let us know if something of the above helps or gives more info to better understand what could be happening here!

**Comment by WenTheProgrammer** [comment]
Here is the list for base environment:
```
# Name                    Version                   Build  Channel
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda-client           1.11.1          py310haa95532_0
anaconda-navigator        2.4.0           py310haa95532_0
anaconda-project          0.11.1          py310haa95532_0
anyio                     3.5.0           py310haa95532_0
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0
arrow                     1.2.3           py310haa95532_1
astroid                   2.14.2          py310haa95532_0
astropy                   5.1             py310h9128911_0
asttokens                 2.0.5              pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0          py310haa95532_0
automat                   20.2.0                     py_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.11.0          py310haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.1                pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0           py310h2bbff1b_1
beautifulsoup4            4.11.1          py310haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     22.6.0          py310haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.3               h6c2663c_0
bokeh                     2.4.3           py310haa95532_0
bottleneck                1.3.5           py310h9128911_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py310h2bbff1b_1002
bzip2                     1.0.8                he774522_0
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7       py310haa95532_0
cffi                      1.15.1          py310h2bbff1b_3
cfitsio                   3.470                h2bbff1b_7
chardet                   4.0.0           py310haa95532_1003
charls                    2.2.0                h6c2663c_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4           py310haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
clyent                    1.2.2           py310haa95532_1
colorama                  0.4.6           py310haa95532_0
colorcet                  3.0.1           py310haa95532_0
comm                      0.1.2           py310haa95532_0
conda                     23.1.0          py310haa95532_0
conda-build               3.23.3          py310haa95532_0
conda-content-trust       0.1.3           py310haa95532_0
conda-pack                0.6.0              pyhd3eb1b0_0
conda-package-handling    2.0.2           py310haa95532_0
conda-package-streaming   0.7.0           py310haa95532_0
conda-repo-cli            1.0.27          py310haa95532_0
conda-token               0.4.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
constantly                15.1.0          py310haa95532_0
contourpy                 1.0.5           py310h59b6b97_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              39.0.1          py310h21b164f_0
cssselect                 1.1.0              pyhd3eb1b0_0
curl                      7.87.0               h2bbff1b_0
cycler                    0.11.0             pyhd3eb1b0_0
cytoolz                   0.12.0          py310h2bbff1b_0
daal4py                   2023.0.2        py310hf497b98_0
dal                       2023.0.1         h59b6b97_26646
dask                      2022.7.0        py310haa95532_0
dask-core                 2022.7.0        py310haa95532_0
datashader                0.14.4          py310haa95532_0
datashape                 0.5.4           py310haa95532_1
debugpy                   1.5.1           py310hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6           py310haa95532_0
distributed               2022.7.0        py310haa95532_0
docstring-to-markdown     0.11            py310haa95532_0
docutils                  0.18.1          py310haa95532_3
entrypoints               0.4             py310haa95532_0
et_xmlfile                1.1.0           py310haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
filelock                  3.9.0           py310haa95532_0
flake8                    6.0.0           py310haa95532_0
flask                     2.2.2           py310haa95532_0
flit-core                 3.6.0              pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
fsspec                    2022.11.0       py310haa95532_0
future                    0.18.3          py310haa95532_0
gensim                    4.3.0           py310h4ed8f06_0
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
glob2                     0.7                pyhd3eb1b0_0
greenlet                  2.0.1           py310hd77b12b_0
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
h5py                      3.7.0           py310hfc34f40_0
hdf5                      1.10.6               h1756f20_1
heapdict                  1.0.1              pyhd3eb1b0_0
holoviews                 1.15.4          py310haa95532_0
huggingface_hub           0.10.1          py310haa95532_0
hvplot                    0.8.2           py310haa95532_0
hyperlink                 21.0.0             pyhd3eb1b0_0
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4             py310haa95532_0
imagecodecs               2021.8.26       py310h4c966c4_2
imageio                   2.26.0          py310haa95532_0
imagesize                 1.4.1           py310haa95532_0
imbalanced-learn          0.10.1          py310haa95532_0
importlib-metadata        4.11.3          py310haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
incremental               21.3.0             pyhd3eb1b0_0
inflection                0.5.1           py310haa95532_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intake                    0.6.7           py310haa95532_0
intel-openmp              2021.4.0          haa95532_3556
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.19.2          py310h9909e9c_0
ipython                   8.10.0          py310haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
itemadapter               0.3.0              pyhd3eb1b0_0
itemloaders               1.0.4              pyhd3eb1b0_1
itsdangerous              2.0.1              pyhd3eb1b0_0
jedi                      0.18.1          py310haa95532_1
jellyfish                 0.9.0           py310h2bbff1b_0
jinja2                    3.1.2           py310haa95532_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jmespath                  0.10.0             pyhd3eb1b0_0
joblib                    1.1.1           py310haa95532_0
jpeg                      9e                   h2bbff1b_1
jq                        1.6                  haa95532_1
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.17.3          py310haa95532_0
jupyter                   1.0.0           py310haa95532_8
jupyter_client            7.3.4           py310haa95532_0
jupyter_console           6.6.2           py310haa95532_0
jupyter_core              5.2.0           py310haa95532_0
jupyter_server            1.23.4          py310haa95532_0
jupyterlab                3.5.3           py310haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.19.0          py310haa95532_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
jxrlib                    1.1                  he774522_2
keyring                   23.4.0          py310haa95532_0
kiwisolver                1.4.4           py310hd77b12b_0
lazy-object-proxy         1.6.0           py310h2bbff1b_0
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libaec                    1.0.4                h33f27b4_1
libarchive                3.6.2                hebabd0d_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  12.0.0          default_h627e005_2
libcurl                   7.87.0               h86230a5_0
libdeflate                1.17                 h2bbff1b_0
libffi                    3.4.2                hd77b12b_6
libiconv                  1.16                 h2bbff1b_2
liblief                   0.12.3               hd77b12b_0
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libssh2                   1.10.0               hcd4344a_0
libtiff                   4.5.0                h6c2663c_2
libuv                     1.44.2               h2bbff1b_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
libzopfli                 1.0.3                ha925a31_0
llvmlite                  0.39.1          py310h23ce68f_0
locket                    1.0.0           py310haa95532_0
lxml                      4.9.1           py310h1985fb9_0
lz4                       3.1.3           py310h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
lzo                       2.10                 he774522_2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.4.1           py310haa95532_0
markupsafe                2.1.1           py310h2bbff1b_0
matplotlib                3.7.0           py310haa95532_0
matplotlib-base           3.7.0           py310h4ed8f06_0
matplotlib-inline         0.1.6           py310haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
menuinst                  1.4.19          py310h59b6b97_0
mistune                   0.8.4           py310h2bbff1b_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
mock                      4.0.3              pyhd3eb1b0_0
mpmath                    1.2.1           py310haa95532_0
msgpack-python            1.0.3           py310h59b6b97_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0           py310haa95532_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3           py310haa95532_1
navigator-updater         0.3.0           py310haa95532_0
nbclassic                 0.5.2           py310haa95532_0
nbclient                  0.5.13          py310haa95532_0
nbconvert                 6.5.4           py310haa95532_0
nbformat                  5.7.0           py310haa95532_0
nest-asyncio              1.5.6           py310haa95532_0
networkx                  2.8.4           py310haa95532_0
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
nltk                      3.7                pyhd3eb1b0_0
notebook                  6.5.2           py310haa95532_0
notebook-shim             0.2.2           py310haa95532_0
numba                     0.56.4          py310h4ed8f06_0
numexpr                   2.8.4           py310hd213c9f_0
numpy                     1.23.5          py310h60c9a35_0
numpy-base                1.23.5          py310h04254f7_0
numpydoc                  1.5.0           py310haa95532_0
openjpeg                  2.4.0                h4fc8c34_0
openpyxl                  3.0.10          py310h2bbff1b_0
openssl                   1.1.1t               h2bbff1b_0
packaging                 22.0            py310haa95532_0
pandas                    1.5.3           py310h4ed8f06_0
pandocfilters             1.5.0              pyhd3eb1b0_0
panel                     0.14.3          py310haa95532_0
param                     1.12.3          py310haa95532_0
paramiko                  2.8.1              pyhd3eb1b0_0
parsel                    1.6.0           py310haa95532_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_1
pathlib                   1.0.1              pyhd3eb1b0_1
pathspec                  0.10.3          py310haa95532_0
patsy                     0.5.3           py310haa95532_0
pcre                      8.45                 hd77b12b_0
pep8                      1.7.1           py310haa95532_1
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.4.0           py310hd77b12b_0
pip                       22.3.1          py310haa95532_0
pkginfo                   1.8.3           py310haa95532_0
platformdirs              2.5.2           py310haa95532_0
plotly                    5.9.0           py310haa95532_0
pluggy                    1.0.0           py310haa95532_1
ply                       3.11            py310haa95532_0
pooch                     1.4.0              pyhd3eb1b0_0
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.14.1          py310haa95532_0
prompt-toolkit            3.0.36          py310haa95532_0
prompt_toolkit            3.0.36               hd3eb1b0_0
protego                   0.1.16                     py_0
psutil                    5.9.0           py310h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0             pyhd3eb1b0_0
py-lief                   0.12.3          py310hd77b12b_0
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pycodestyle               2.10.0          py310haa95532_0
pycosat                   0.6.4           py310h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pyct                      0.5.0           py310haa95532_0
pycurl                    7.45.1          py310hcd4344a_0
pydispatcher              2.0.5           py310haa95532_2
pydocstyle                6.3.0           py310haa95532_0
pyerfa                    2.0.0           py310h2bbff1b_0
pyflakes                  3.0.1           py310haa95532_0
pygments                  2.11.2             pyhd3eb1b0_0
pyhamcrest                2.0.2              pyhd3eb1b0_2
pyjwt                     2.4.0           py310haa95532_0
pylint                    2.16.2          py310haa95532_0
pylint-venv               2.3.0                    pypi_0    pypi
pyls-spyder               0.4.0              pyhd3eb1b0_0
pynacl                    1.5.0           py310h8cc25b3_0
pyodbc                    4.0.34          py310hd77b12b_0
pyopenssl                 23.0.0          py310haa95532_0
pyparsing                 3.0.9           py310haa95532_0
pyqt                      5.15.7          py310hd77b12b_0
pyqt5-sip                 12.11.0         py310hd77b12b_0
pyqtwebengine             5.15.7          py310hd77b12b_0
pyrsistent                0.18.0          py310h2bbff1b_0
pysocks                   1.7.1           py310haa95532_0
pytables                  3.7.0           py310h388bc9b_1
pytest                    7.1.2           py310haa95532_0
python                    3.10.9               h966fe2a_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py310haa95532_0
python-libarchive-c       2.9                pyhd3eb1b0_1
python-lsp-black          1.2.1           py310haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.7.1           py310haa95532_0
python-slugify            5.0.2              pyhd3eb1b0_0
python-snappy             0.6.1           py310hd77b12b_0
pytoolconfig              1.2.5           py310haa95532_1
pytorch                   1.12.1          cpu_py310h5e1f01c_1
pytz                      2022.7          py310haa95532_0
pyviz_comms               2.0.2              pyhd3eb1b0_0
pywavelets                1.4.1           py310h2bbff1b_0
pywin32                   305             py310h2bbff1b_0
pywin32-ctypes            0.2.0           py310haa95532_1000
pywinpty                  2.0.10          py310h5da7b33_0
pyyaml                    6.0             py310h2bbff1b_1
pyzmq                     23.2.0          py310hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2                    pypi_0    pypi
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_5
qtawesome                 1.2.2                    pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.2.0           py310haa95532_0
qtwebkit                  5.212                h3ad3cdb_4
queuelib                  1.5.0           py310haa95532_0
regex                     2022.7.9        py310h2bbff1b_0
requests                  2.28.1          py310haa95532_0
requests-file             1.5.1              pyhd3eb1b0_0
rope                      1.7.0           py310haa95532_0
rtree                     1.0.1           py310h2eaa2aa_0
ruamel.yaml               0.17.21         py310h2bbff1b_0
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1
ruamel_yaml               0.17.21         py310h2bbff1b_0
scikit-image              0.19.3          py310hd77b12b_1
scikit-learn              1.2.1           py310hd77b12b_0
scikit-learn-intelex      2023.0.2        py310haa95532_0
scipy                     1.10.0          py310hb9afe5d_1
scrapy                    2.8.0           py310haa95532_0
seaborn                   0.12.2          py310haa95532_0
send2trash                1.8.0              pyhd3eb1b0_1
service_identity          18.1.0             pyhd3eb1b0_1
setuptools                65.6.3          py310haa95532_0
sip                       6.6.2           py310hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smart_open                5.2.1           py310haa95532_0
snappy                    1.1.9                h6c2663c_0
sniffio                   1.2.0           py310haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.2.post1     py310haa95532_0
sphinx                    5.0.2           py310haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.4.1           py310haa95532_0
spyder-kernels            2.4.1           py310haa95532_0
sqlalchemy                1.4.39          py310h2bbff1b_0
sqlite                    3.40.1               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
statsmodels               0.13.5          py310h9128911_1
sympy                     1.11.1          py310haa95532_0
tabulate                  0.8.10          py310haa95532_0
tbb                       2021.7.0             h59b6b97_0
tbb4py                    2021.7.0        py310h59b6b97_0
tblib                     1.7.0              pyhd3eb1b0_0
tenacity                  8.0.1           py310haa95532_1
terminado                 0.17.1          py310haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2021.7.2           pyhd3eb1b0_2
tinycss2                  1.2.1           py310haa95532_0
tk                        8.6.12               h2bbff1b_0
tldextract                3.2.0              pyhd3eb1b0_0
tokenizers                0.11.4          py310he5181cf_1
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1           py310haa95532_0
tomlkit                   0.11.1          py310haa95532_0
toolz                     0.12.0          py310haa95532_0
tornado                   6.1             py310h2bbff1b_0
tqdm                      4.64.1          py310haa95532_0
traitlets                 5.7.1           py310haa95532_0
transformers              4.24.0          py310haa95532_0
twisted                   22.2.0          py310h2bbff1b_1
twisted-iocpsupport       1.0.2           py310h2bbff1b_0
typing-extensions         4.4.0           py310haa95532_0
typing_extensions         4.4.0           py310haa95532_0
tzdata                    2022g                h04d1e81_0
ujson                     5.4.0           py310hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.14         py310haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
w3lib                     1.21.0             pyhd3eb1b0_0
watchdog                  2.1.6           py310haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py310haa95532_1
websocket-client          0.58.0          py310haa95532_4
werkzeug                  2.2.2           py310haa95532_0
whatthepatch              1.0.2           py310haa95532_0
wheel                     0.38.4          py310haa95532_0
widgetsnbextension        3.5.2           py310haa95532_0
win_inet_pton             1.1.0           py310haa95532_0
wincertstore              0.2             py310haa95532_2
winpty                    0.4.3                         4
wrapt                     1.14.1          py310h2bbff1b_0
xarray                    2022.11.0       py310haa95532_0
xlwings                   0.29.1          py310haa95532_0
xz                        5.2.10               h8cc25b3_1
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.4                hd77b12b_0
zfp                       0.5.5                hd77b12b_6
zict                      2.1.0           py310haa95532_0
zipp                      3.11.0          py310haa95532_0
zlib                      1.2.13               h8cc25b3_0
zope                      1.0             py310haa95532_1
zope.interface            5.4.0           py310h2bbff1b_0
zstandard                 0.19.0          py310h2bbff1b_0
zstd                      1.5.2                h19a0ad4_0
```
Here is the list for tf environment:
```
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
alabaster                 0.7.12             pyhd3eb1b0_0
arrow                     1.2.3            py39haa95532_1
astroid                   2.14.2           py39haa95532_0
asttokens                 2.0.5              pyhd3eb1b0_0
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                      py_0
attrs                     22.1.0           py39haa95532_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.11.0           py39haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
bcrypt                    3.2.0            py39h2bbff1b_1
beautifulsoup4            4.12.0           py39haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     23.3.0           py39haa95532_0
bleach                    4.1.0              pyhd3eb1b0_0
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2023.01.10           haa95532_0
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7        py39haa95532_0
cffi                      1.15.1           py39h2bbff1b_3
chardet                   4.0.0           py39haa95532_1003
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.0.4            py39haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
colorama                  0.4.6            py39haa95532_0
comm                      0.1.2            py39haa95532_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              39.0.1           py39h21b164f_0
cudatoolkit               11.2.2              h933977f_10    conda-forge
cudnn                     8.1.0.77             h3e0f4f4_0    conda-forge
debugpy                   1.5.1            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6            py39haa95532_0
docstring-to-markdown     0.11             py39haa95532_0
docutils                  0.18.1           py39haa95532_3
entrypoints               0.4              py39haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
flake8                    6.0.0            py39haa95532_0
flatbuffers               23.3.3                   pypi_0    pypi
flit-core                 3.8.0            py39haa95532_0
gast                      0.4.0                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
google-auth               2.17.2                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.53.0                   pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
h5py                      3.8.0                    pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      3.4              py39haa95532_0
imagesize                 1.4.1            py39haa95532_0
importlib-metadata        6.3.0                    pypi_0    pypi
importlib_metadata        6.0.0                hd3eb1b0_0
inflection                0.5.1            py39haa95532_0
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.19.2           py39hd4e2768_0
ipython                   8.12.0           py39haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jaraco.classes            3.2.1              pyhd3eb1b0_0
jedi                      0.18.1           py39haa95532_1
jellyfish                 0.9.0            py39h2bbff1b_0
jinja2                    3.1.2            py39haa95532_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jpeg                      9e                   h2bbff1b_1
jsonschema                4.17.3           py39haa95532_0
jupyter_client            7.4.9            py39haa95532_0
jupyter_core              5.3.0            py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   23.13.1          py39haa95532_0
krb5                      1.19.4               h5b6d351_0
lazy-object-proxy         1.6.0            py39h2bbff1b_0
lerc                      3.0                  hd77b12b_0
libclang                  16.0.0                   pypi_0    pypi
libclang13                14.0.6          default_h8e68704_1
libdeflate                1.17                 h2bbff1b_0
libffi                    3.4.2                hd77b12b_6
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libtiff                   4.5.0                h6c2663c_2
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
libxml2                   2.10.3               h0ad7f3c_0
libxslt                   1.1.37               h2bbff1b_0
lxml                      4.9.2            py39h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib-inline         0.1.6            py39haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
mistune                   0.8.4           py39h2bbff1b_1000
more-itertools            8.12.0             pyhd3eb1b0_0
mypy_extensions           0.4.3            py39haa95532_1
nbclient                  0.5.13           py39haa95532_0
nbconvert                 6.5.4            py39haa95532_0
nbformat                  5.7.0            py39haa95532_0
nest-asyncio              1.5.6            py39haa95532_0
numpy                     1.24.2                   pypi_0    pypi
numpydoc                  1.5.0            py39haa95532_0
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.0             py39haa95532_0
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.10.3           py39haa95532_0
pcre                      8.45                 hd77b12b_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       23.0.1           py39haa95532_0
platformdirs              2.5.2            py39haa95532_0
pluggy                    1.0.0            py39haa95532_1
ply                       3.11             py39haa95532_0
poyo                      0.5.0              pyhd3eb1b0_0
prompt-toolkit            3.0.36           py39haa95532_0
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.0            py39h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.10.0           py39haa95532_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.3.0            py39haa95532_0
pyflakes                  3.0.1            py39haa95532_0
pygments                  2.11.2             pyhd3eb1b0_0
pylint                    2.16.2           py39haa95532_0
pylint-venv               2.3.0            py39haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pynacl                    1.5.0            py39h8cc25b3_0
pyopenssl                 23.0.0           py39haa95532_0
pyqt                      5.15.7           py39hd77b12b_0
pyqt5-sip                 12.11.0          py39hd77b12b_0
pyqtwebengine             5.15.7           py39hd77b12b_0
pyrsistent                0.18.0           py39h196d8e1_0
pysocks                   1.7.1            py39haa95532_0
python                    3.9.16               h6244533_2
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39haa95532_0
python-lsp-black          1.2.1            py39haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.7.1            py39haa95532_0
python-slugify            5.0.2              pyhd3eb1b0_0
pytoolconfig              1.2.5            py39haa95532_1
pytz                      2022.7           py39haa95532_0
pywin32                   305              py39h2bbff1b_0
pywin32-ctypes            0.2.0           py39haa95532_1000
pyyaml                    6.0              py39h2bbff1b_1
pyzmq                     23.2.0           py39hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2            py39haa95532_0
qt-main                   5.15.2               he8e5bd7_8
qt-webengine              5.15.9               hb9a9bb5_5
qtawesome                 1.2.2            py39haa95532_0
qtconsole                 5.4.0            py39haa95532_0
qtpy                      2.2.0            py39haa95532_0
qtwebkit                  5.212                h2bbfb41_5
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rope                      1.7.0            py39haa95532_0
rsa                       4.9                      pypi_0    pypi
rtree                     1.0.1            py39h2eaa2aa_0
setuptools                65.6.3           py39haa95532_0
sip                       6.6.2            py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.4              py39haa95532_0
sphinx                    5.0.2            py39haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.4.2            py39haa95532_0
spyder-kernels            2.4.2            py39haa95532_0
sqlite                    3.41.1               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.1                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss2                  1.2.1            py39haa95532_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py39haa95532_0
tomlkit                   0.11.1           py39haa95532_0
tornado                   6.2              py39h2bbff1b_0
traitlets                 5.7.1            py39haa95532_0
typing-extensions         4.5.0                    pypi_0    pypi
typing_extensions         4.4.0            py39haa95532_0
tzdata                    2023c                h04d1e81_0
ujson                     5.4.0            py39hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.15          py39haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.6            py39haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
werkzeug                  2.2.3                    pypi_0    pypi
whatthepatch              1.0.2            py39haa95532_0
wheel                     0.38.4           py39haa95532_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
wrapt                     1.15.0                   pypi_0    pypi
xz                        5.2.10               h8cc25b3_1
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.4                hd77b12b_0
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.4                hd43e919_0
```
My installed tensorflow version is 2.10.1. I have tensorflow installed only in the tf environment though. I checked both Spyders, and there is no entry in their PYTHONPATH managers.

**Comment by dalthviz** [comment]
Checking with more attention the message you are getting from `tensorflow`, seems like it is unable to access some dynamic libraries. Seems like you installed `tensorflow` using pip which probably could be causing troubles 🤔 

Maybe this guide could be useful: https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

I would suggest to try to create an env that uses only conda packages and check if the issue persist following the guide above. Let us know if that helps!

**Comment by WenTheProgrammer** [comment]
Since my two Spyders have different versions, I am able to see that my Windows’ Spyder shortcut would open the Spyder installed under base environment. Previously I changed my base Spyder’s default environment from base to tf, which is giving the errors that I showed above when detecting GPU. Maybe running Spyder installed under one environment in a different environment is causing the problem?

**Comment by dalthviz** [comment]
Maybe something could be happening with the env activation inside Spyder 🤔 However, just to be sure and discard that your env is faulty, could you please try to run the code to check the GPU from outside Spyder in a Python interpreter from an anaconda prompt with your `tf` env activated and let us know if it shows the same message related with the missing dynamic libraries or if detects correctly the GPU?

**Comment by WenTheProgrammer** [comment]
GPU can be correctly detected in that case:
![image](https://user-images.githubusercontent.com/67032259/231632226-b1eed453-58c2-412a-bb75-3b93cd5a29ba.png)

**Comment by dalthviz** [comment]
Thank you for testing @WenTheProgrammer ! Maybe then this could be related with https://github.com/spyder-ide/spyder/issues/16562? Did you install anaconda for all the users?. Also, could you compare the contents of `sys.path` from inside the Spyder IPython console and the `sys.path` returned from the Python interpreter from the anaconda prompt?

**Comment by WenTheProgrammer** [comment]
Interestingly there is a differece.
Anaconda Prompt:
```
>>> import sys
>>> sys.path
['', 'C:\\Users\\wenan\\anaconda3\\python310.zip', 'C:\\Users\\wenan\\anaconda3\\DLLs', 'C:\\Users\\wenan\\anaconda3\\lib', 'C:\\Users\\wenan\\anaconda3', 'C:\\Users\\wenan\\anaconda3\\lib\\site-packages', 'C:\\Users\\wenan\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\wenan\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\wenan\\anaconda3\\lib\\site-packages\\Pythonwin']
```
Spyder:
```
import sys
The system cannot find the path specified.
```

**Comment by dalthviz** [comment]
Thanks for the new info! Could it be possible for you to reinstall Spyder in your base environment and check again?. Also, now Spyder 5.4.3 is available from the default anaconda channel so you can install the latest version. Besides that, as a workaround of your base env, you should have a shortcut to launch Spyder from your `tf` environment. You should be able to get it in the star menu by searching `Spyder (tf)`

Let us now if something of the suggestions above is useful!

**Comment by WenTheProgrammer** [comment]
Reinstalling Spyder in base gives the following error when I open Spyder:
![image](https://user-images.githubusercontent.com/67032259/232344585-99394b62-0e2a-44f9-a255-702ae065c539.png)
However, this time it shows all the system paths as the Spyder in tf environment, and is able to detect GPU successfully.
Using the Spyder (tf) shortcut certainly works for my problem too.

**Comment by WenTheProgrammer** [comment]
The Spyder installed in tf environment also shows the same error now...

**Comment by GrayCyberWildman** [comment]
> The Spyder installed in tf environment also shows the same error now... It seems to be an error that comes with Spyder 5.4.3?

I think the dependency error here is another problem. The same problem also occurs in my base environment. Currently, the latest version of pylsp provided by the anaconda (main) channel is 1.7.1, which in my opinion causes this error.
Anyway, in conclusion, it seems that reinstalling Spyder has solved the problem you encountered. Congratulations!

**Comment by dalthviz** [comment]
Seems like you manage to fix the problem with Tensorflow @WenTheProgrammer ! But yes as @GrayCyberWildman (thanks for pointing that out!) the other error message you are now seeing comes from the anaconda default channel not having yet `pylsp` 1.7.2 package version (which is an updated dependency constraint for Spyder 5.4.3). You can check the versions available for that package at https://anaconda.org/anaconda/python-lsp-server (still as far as I checked the latest version there is 1.7.1). There is not much we can do from the Spyder side, sorry :/ You will need to wait for anaconda to upload the 1.7.2 version of that package. After that you will be able to update that package (pylsp - python-lsp-server) to prevent the error from showing. The other think you could is to create a new env but using only packages from the conda-forge channel pylsp version 1.7.2 is availble there.

Let us know if the info above helps clarify the situation!

**Comment by WenTheProgrammer** [comment]
Thank you @dalthviz and @GrayCyberWildman!
